# Numpy Array

In [5]:
import numpy as np

In [2]:
np.array(["vbhvh", 2, 3])

array(['vbhvh', '2', '3'], dtype='<U5')

In [3]:
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [4]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [5]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [7]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x # 1 follow a and 2 follow b

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [9]:
type(x[1][0])

numpy.int16

In [10]:
np.mat(np.array([[1, 2],[4,7]])) #create matrix from array

matrix([[1, 2],
        [4, 7]])

In [11]:
np.mat('1 2; 3 4;4 5') #create matrix from string

matrix([[1, 2],
        [3, 4],
        [4, 5]])

# numpy.asarray

In [6]:
a = [1, 2]
a = np.array([1, 2])
a

array([1, 2])

In [7]:
np.asarray((1,2)) #asarray and array function create ndarray type output

array([1, 2])

In [8]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [9]:
np.asarray(a, dtype=np.float64) is a

False

In [10]:
issubclass(np.matrix, np.ndarray)

True

In [11]:
a = np.matrix([[1, 2]])
np.asanyarray(a)

matrix([[1, 2]])

In [12]:
np.asarray(a) is a

False

In [13]:
np.asanyarray(a) is a

True

In [14]:
type(np.asarray(a))

numpy.ndarray

In [16]:
type(np.array(a))

numpy.ndarray

In [15]:
type(np.asanyarray(a))

numpy.matrix

# numpy.asanyarray
it will convert list to an array, but if the input is already array/matrix it will do anything

In [23]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [21]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [22]:
np.asanyarray([1,2]) is a

False

In [24]:
np.array(a, copy=True) # it will create a seperate instane and load it there

array([1, 2])

In [25]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [26]:
y = x
y

array([1, 2, 3])

In [27]:
z = np.copy(x) # create a new space and copy the data there
z

array([1, 2, 3])

In [28]:
y[0] = 100
x

array([100,   2,   3])

In [29]:
y

array([100,   2,   3])

In [30]:
z

array([1, 2, 3])

In [31]:
z[0]=2222
z

array([2222,    2,    3])

In [32]:
x

array([100,   2,   3])

# numpy.fromfunction

In [33]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [35]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000023DEF67E5C8>

In [36]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [37]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [38]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [39]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [40]:
print(r[1]["a"])

2


In [41]:
type(r)

numpy.recarray

In [42]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [43]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


# arange and linspace

In [44]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [45]:
list(range(5,16,2.3)) #difference between range and arange function

TypeError: 'float' object cannot be interpreted as an integer

In [46]:
np.arange(0,11,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [47]:
print((np.linspace(1,5,50))) #50 linearly spaced numbers between 1 and 5

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [48]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [49]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [51]:
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [52]:
print(5+np.ones((3,5)))

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [54]:
np.empty((6,5)) #give random output

array([[1.21787280e-311, 9.63428009e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [5.02034658e+175, 1.90226942e+185, 4.22780575e-062,
        2.37942202e+184, 1.29206045e+161],
       [5.01163107e+217, 5.49419094e-143, 9.80058441e+252,
        6.52022889e+252, 1.06396443e+224],
       [1.47765135e+248, 4.30625279e-096, 9.08366793e+223,
        7.11403229e-038, 5.25098212e+170],
       [4.50276459e-033, 9.91875511e+164, 2.24729347e+174,
        1.56605686e-076, 1.65612025e-076],
       [1.48330705e-071, 6.52516844e-038, 1.28625693e+248,
        4.24948967e-086, 4.05171132e-317]])

In [55]:
mat1 = np.eye(4)
mat1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.arange(3)

array([0, 1, 2])

In [57]:
np.arange(3.0)

array([0., 1., 2.])

In [58]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [59]:
np.linspace(2.0, 3.0, num=5, endpoint=False) #ignore the uplimit

array([2. , 2.2, 2.4, 2.6, 2.8])

In [60]:
np.linspace(2.0, 3.0, num=9, retstep=True) #it will provide the stepsize

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [61]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [63]:
x = np.arange(16).reshape((-1,4))
#Extract a diagonal or construct a diagonal array.-any negative no it will autocalculate the remaning items
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.diag(x) #it willprovide diagonal data

array([ 0,  5, 10, 15])

In [65]:
np.diag(x, k=2)

array([2, 7])

In [66]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [67]:
np.diag(np.diag(x))# calling twice it will create matrix

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [68]:
#Create a two-dimensional array with the flattened input as a diagonal.
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [69]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [71]:
np.tri(3, 5, 0, dtype=int) #create trigonal matrix

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [73]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [74]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [75]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)#return a Lower triangle of an array.

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [76]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)#return Upper triangle of an array.

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [78]:
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary

[[0.12432909 0.4200738  0.12854645]
 [0.13835682 0.08002988 0.3218776 ]]


In [79]:
print(np.random.randn(4,3))

[[ 0.62996168 -0.82190765 -1.18785554]
 [ 0.40275827  1.32806132 -0.46904018]
 [-0.85615271  0.30070481  1.14314816]
 [ 0.22592019 -0.18284284  1.6221666 ]]


In [80]:
np.random.randint(1,10)

8

In [81]:
np.random.randint(1,100,(4,4))

array([[44, 81, 19, 23],
       [20, 32, 40, 46],
       [ 1,  4, 83, 11],
       [ 5, 60, 51, 23]])

# Reshaping

In [6]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[92, 92, 88, 71, 23],
       [75,  7, 96, 71, 83],
       [65, 96, 88, 87, 21],
       [85,  5, 40, 48, 63],
       [ 9, 21, 11, 17, 56],
       [ 4, 91, 11, 51, 53]])

In [7]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [23 54 91 13  8 33 27 66 63 16]

Here is the sorted vector
 -------------------------------------------------- 
 [ 8 13 16 23 27 33 54 63 66 91]


In [8]:
M = ri(1,100,25).reshape(5,5)
np.sort(M, axis=1, kind='mergesort')

array([[52, 62, 76, 85, 87],
       [22, 22, 57, 90, 94],
       [24, 37, 44, 79, 98],
       [14, 21, 91, 99, 99],
       [23, 32, 39, 47, 76]])

In [9]:
print("Max of a:", M.max())
print("Max of b:", b.max())

Max of a: 99
Max of b: 96


In [12]:
M

array([[52, 62, 87, 76, 85],
       [22, 57, 90, 22, 94],
       [24, 44, 79, 98, 37],
       [14, 21, 99, 99, 91],
       [76, 23, 32, 39, 47]])

In [11]:
print("Max of a location:", M.argmax(axis= 0))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())
#it return the index axis 0 - row wise **WHEN YOU CHOOSE COLUMN WISE THEN IT WILL FIRST SELECT THE FIRST ROW THE ARANGE IT BETWEEN DIFFRENT COLUMNS, SAME WAY REPEATE FOR ALL THE ROWS**

Max of a location: [4 0 3 3 1]
Max of b location: 7
Max of c location: 7


# Indexing and slicing

In [16]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[7]

7

In [18]:
arr[3:6:2]

array([3, 5])

In [19]:
arr[-1:-6:2]

array([], dtype=int32)

In [20]:
arr = np.arange(0,21,2)

In [21]:
arr[[2,4,9]]# Pass a list as a index to subset
#Elements at 2nd, 4th, and 9th index are

array([ 4,  8, 18])

In [23]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[10, 87, 74, 88, 65],
       [70, 67, 12, 12, 77],
       [75, 25, 22, 65, 48]])

In [24]:
mat[1:4,3:5]

array([[12, 77],
       [65, 48]])

In [25]:
mat[0:3,[1,3]]

array([[87, 88],
       [67, 12],
       [25, 65]])

In [26]:
mat[1][1]

67

In [27]:
mat[:,3]

array([88, 12, 65])

In [28]:
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[12 77]
 [65 48]]


In [29]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[87 88]
 [67 12]]


# Subseting

In [30]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[98 86 81 74 23]
 [40 45 78 92 67]
 [68 61 63 76 38]]


array([[ True,  True,  True,  True, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [31]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [98 86 81 74 78 92 67 68 61 63 76]


# Slicing

In [32]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [33]:
mat_slice = mat[:2,:2]
print(mat_slice)

[[11 12]
 [21 22]]


In [34]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


# Universal Functions

In [35]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[7 3 7]
 [1 4 3]
 [8 4 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 2 6]
 [3 1 7]
 [6 6 1]]


In [36]:
mat1*mat2

array([[42,  6, 42],
       [ 3,  4, 21],
       [48, 24,  9]])

In [37]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)


Addition
------------------
 [[13  5 13]
 [ 4  5 10]
 [14 10 10]]

Multiplication
------------------
 [[ 93  59  70]
 [ 36  24  37]
 [114  74  85]]


In [38]:
mat1/0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [39]:
100+mat1

array([[107, 103, 107],
       [101, 104, 103],
       [108, 104, 109]])

In [40]:
mat1**3#Exponentiation, matrix cubed here

array([[343,  27, 343],
       [  1,  64,  27],
       [512,  64, 729]], dtype=int32)

In [41]:
pow(mat1,3)#Exponentiation, sq-root using pow function

array([[343,  27, 343],
       [  1,  64,  27],
       [512,  64, 729]], dtype=int32)

# Broadcasting

In [42]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [43]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [44]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [45]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [46]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [47]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [50]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [51]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


1st Matrix of random single-digit numbers

 [[3 6 7]
 [3 7 1]
 [3 8 4]]

2nd Matrix of random single-digit numbers
------------
 [[4 7 1]
 [8 2 6]
 [8 1 6]]


In [52]:
np.sqrt(mat1)

array([[1.73205081, 2.44948974, 2.64575131],
       [1.73205081, 2.64575131, 1.        ],
       [1.73205081, 2.82842712, 2.        ]])

In [54]:
np.exp(mat1)

array([[2.00855369e+01, 4.03428793e+02, 1.09663316e+03],
       [2.00855369e+01, 1.09663316e+03, 2.71828183e+00],
       [2.00855369e+01, 2.98095799e+03, 5.45981500e+01]])

In [53]:
np.log10(mat1)

array([[0.47712125, 0.77815125, 0.84509804],
       [0.47712125, 0.84509804, 0.        ],
       [0.47712125, 0.90308999, 0.60205999]])

In [55]:
np.fmod(mat1,mat2) #same as below

array([[3, 6, 0],
       [3, 1, 1],
       [3, 0, 4]], dtype=int32)

In [56]:
mat1%mat2

array([[3, 6, 0],
       [3, 1, 1],
       [3, 0, 4]], dtype=int32)

In [57]:
np.linspace(0,12*np.pi,1001)

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])